# Generated by Django 4.1 on 2022-09-03 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome do Produto')),
                ('category', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Infantil', 'Infantil')], max_length=9, verbose_name='Categoria')),
                ('size', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('P M', 'P M'), ('P G', 'P G'), ('M G', 'M G'), ('P M G', 'P M G')], max_length=5, verbose_name='Tamanho')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Preço')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(upload_to='product/')),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Favorito')),
            ],
        ),
    ]
